### ISSUE TITLE
🐛 Bug report: Navigation scrolls below the about section.

### ISSUE THREAD

**Issue by sarojregmi200** [GNOME-Nepal/website#13]
**Describe the bug**
The navigation in the website scrolls from behind the about section.

**To Reproduce**
1. Go to 'https://gnome-nepal.vercel.app/'
1. Scroll down to 'About'

**Expected behavior**
The Nav should always be at the top.

**Screenshots**
![20240811_15h17m07s_grim](https://github.com/user-attachments/assets/ceaf5959-3ab9-40ea-bb3d-c5ca2ba9ba42)

**Device information**
 - OS: [ Arch linux ]
 - Browser [ Firefox ]
 - Version [ 125.0.3 ]

**Comment by utsavdotdev** [comment]
Hi @sarojregmi, Thank you for reporting the issue. We’ve assigned you to fix it. Your contribution is greatly appreciated
