### ISSUE TITLE
🚀 Feature request: Highlight Active Link in Sticky Nav on Scroll

### ISSUE THREAD

**Issue by utsavdotdev** [GNOME-Nepal/website#16]
**Is your feature request related to a problem? Please describe.**
The sticky navigation bar does not update the active link based on the section currently in view, which makes it difficult for users to track their position on the single-page website.

**Describe the solution you'd like**
Update the sticky navigation bar to change the active link based on the section of the page that is currently visible while scrolling.

**Describe alternatives you've considered**
Consider adding a progress indicator or a "Back to Top" button as alternative navigation aids.

**Additional context**
This feature would improve navigation and user experience by providing clear indication of the current section in view.

**Comment by sarojregmi200** [comment]
I would love to work on this issue.

**Comment by utsavdotdev** [comment]
OK that's awesome, I will assigned to you
