### ISSUE TITLE
🚀 Feature request: Improve Mobile Layout for Home and About Sections

### ISSUE THREAD

**Issue by utsavdotdev** [GNOME-Nepal/website#17]
**Is your feature request related to a problem? Please describe.**
The current layout of the Home and About sections does not adapt well to mobile view, affecting usability and readability on smaller screens.

**Describe the solution you'd like**
Redesign the layout of the Home and About sections to enhance mobile view portability, ensuring better readability and user experience on smaller screens.

**Describe alternatives you've considered**
Alternative layout designs or adjustments can be explored to improve mobile responsiveness.

**Additional context**
Screenshots of the current mobile layout are attached for reference. Modifying the layout as shown will enhance usability on mobile devices.

![Screenshot from 2024-08-12 20-04-46](https://github.com/user-attachments/assets/4abc0a24-05f9-4a74-87a4-69f29ae3b9f2)

![Screenshot from 2024-08-12 20-05-10](https://github.com/user-attachments/assets/3d613982-ca20-427d-8804-27dec30fc0df)

**Comment by sarojregmi200** [comment]
I think reducing the padding in the sides and making the text left aligned will help with the readability problem in the mobile view.

I would love to research further more about using different layouts.

**Comment by utsavdotdev** [comment]
Sure!

**Comment by kshetritej** [comment]
> **Is your feature request related to a problem? Please describe.** The current layout of the Home and About sections does not adapt well to mobile view, affecting usability and readability on smaller screens.
> 
> **Describe the solution you'd like** Redesign the layout of the Home and About sections to enhance mobile view portability, ensuring better readability and user experience on smaller screens.
> 
> **Describe alternatives you've considered** Alternative layout designs or adjustments can be explored to improve mobile responsiveness.
> 
> **Additional context** Screenshots of the current mobile layout are attached for reference. Modifying the layout as shown will enhance usability on mobile devices.
> 
> ![Screenshot from 2024-08-12 20-04-46](https://private-user-images.githubusercontent.com/95236817/357084492-4abc0a24-05f9-4a74-87a4-69f29ae3b9f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDkyODIsIm5iZiI6MTcyODM0ODk4MiwicGF0aCI6Ii85NTIzNjgxNy8zNTcwODQ0OTItNGFiYzBhMjQtMDVmOS00YTc0LTg3YTQtNjlmMjlhZTNiOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAwNTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMmIwNThjNjliMTAwZTE3YzJiMjhlN2FlNWNhMTRhOGEyNjNjMjkzNTExMDc4ZDdkMjM2MzY4MTEyYTdhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V4MD2wMQKrnDQPQ5f4HAXxpwPVxSE7vpxUlcFAMa7gs)
> 
> ![Screenshot from 2024-08-12 20-05-10](https://private-user-images.githubusercontent.com/95236817/357084574-3d613982-ca20-427d-8804-27dec30fc0df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDkyODIsIm5iZiI6MTcyODM0ODk4MiwicGF0aCI6Ii85NTIzNjgxNy8zNTcwODQ1NzQtM2Q2MTM5ODItY2EyMC00MjdkLTg4MDQtMjdkZWMzMGZjMGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAwNTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTY2YzQyYTFlZTY5YzFhOGY4ZmM1ZjlhNjc3OGMwODg2OTE0YmYwMzc3OTM0MDUxNTNiYjA2MGE3NzhiZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3H6g9mwRRWGTaXTKDKKGOgEGT0Al8KF8DgYPw70Zk7s)

I am working on this. 
As alternative layouts I would consider left alignments of texts over center alignment.
!And If approved I would like to use shadcn for the accordion and badges too.

>> Left Alignment
![image](https://github.com/user-attachments/assets/f7a80e67-e99a-4242-8d3a-0aa6fb1b5719)

>> Center as of current
![image](https://github.com/user-attachments/assets/51180ab5-dba4-4d8d-bd04-121fa4bcd3c4)

**Comment by utsavdotdev** [comment]
Thanks for the contribution @kshetritej
