### ISSUE TITLE
🚀 Feature request: Optimize SEO of the website Based on Current SEO Report

### ISSUE THREAD

**Issue by utsavdotdev** [GNOME-Nepal/website#18]
**Is your feature request related to a problem? Please describe.**
The current SEO performance of the website is not meeting expectations, as highlighted in the attached SEO report. This affects the site's search engine visibility and ranking.

**Describe the solution you'd like**
Implement SEO optimizations based on the findings in the attached SEO report. Focus on improving key areas such as meta tags, keywords, site structure, and page speed to enhance search engine ranking and visibility.

**Describe alternatives you've considered**
None

**Additional context**
The current SEO report is attached for reference. Addressing the issues outlined in the report will improve overall SEO performance.

- Mobile Seo Report: [Download](https://github.com/user-attachments/files/16588321/seo.pdf)
- Desktop Seo Report: [Download](https://github.com/user-attachments/files/16588363/seodesktop.pdf)

**Comment by sarojregmi200** [comment]
This will surely be very fun I see myself enjoying crushing these bugs can I get assigned to solve this issue.

**Comment by utsavdotdev** [comment]
Assigned!

**Comment by sarojregmi200** [comment]
Will take some time off for this one and submit a good pr. It will require some digging in.
