### ISSUE TITLE
Multiple minor issues: typographical error, regression in image quality, hierarchy issue.

### ISSUE THREAD

**Issue by sudanchapagain** [GNOME-Nepal/website#21]
Opening just one issue for all these minor problems as they really are minor.

## Issue 1: Texts

**Typo 1**

Typo in main section's SVG artwork containing Name of Org and Sub-heading. The typo is in the sub-heading.

```diff
- A Organization which core goals is to promote open source in Nepal
+ An organization whose core goals are to promote open source in Nepal.
```

**Typo 2**

In FAQ's "What is GNOME Nepal"

```diff
- Gnome Nepal is the open source organization whose main motive is to spread collaboration and open source in Nepal.
+ GNOME Nepal is an open source organization whose main motive is to spread collaboration and open source in Nepal.
```

**Typo 3**

FAQ's second question

```diff
- How we can join this Community?
+ How can we join this community?
OR
+ How can I join this community?
```

**Typo 4**

FAQ's last question should be re-written entirely.

```diff
- Is there are exciting event?
+ Are there any exciting events coming up?
```

**Enhancement 1**

Use a concise version of OSI's open-source definition in FAQ's open-source definition.

**Enchancement 2**

text can be refined for empty state of calendar. The current text isn't as clear as it should be.

```diff
- Check back later for new events.
+ Please check back later for updates on new events.
```

## Issue 2: Image quality

The latest PR has regressed the image quality of Group photo greatly. People's faces are pixelated. A bit more pixels are affordable. 

## Issue 3: Hierarchy

The text below the banner image is at 16px but text in FAQ section is 18px. That does not make sense. A better typographical hierarchy must be established at the very least for the "Who we are" and "Our mission" section.

**Comment by utsavdotdev** [comment]
Thanks for pointing this out, @sudanchapagain. Can you work on resolving it? I’ll assign it to you

**Comment by sudanchapagain** [comment]
I have fixed the typo and image regression and opened a PR [https://github.com/GNOME-Nepal/website/pull/22](https://github.com/GNOME-Nepal/website/pull/22) . However, i will not be dealing with the design issues.
