### ISSUE TITLE
🐛 Bug report: Redirection Bug 

### ISSUE THREAD

**Issue by sarojregmi200** [GNOME-Nepal/website#24]
**Describe the bug**
Go to the landing page of [Gnome Nepal](https://gnomenepal.netlify.app/) scroll twice or thrice to the top and the bottom of the page. Now you cannot go back in your history outside the gnome site.

**To Reproduce**
1. Go to the landing page of [Gnome Nepal](https://gnomenepal.netlify.app/) 
1. scroll twice or thrice to the top and the bottom of the page.
1. Now try to go back in history to the search or home page of your browser in the same tab by clicking the back button alongside the url bar.
1. See the error.

**Expected behavior**
Users should be able to exit the site immediately if they have not visited any other routes in the site.

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser: zen

**Additional context**
Here is a video showing the 
problem. 

https://github.com/user-attachments/assets/94b39516-031c-41ce-a6cb-f9123063044c

**Comment by sarojregmi200** [comment]
It is also the same if you click the links in the top navigation.
It is because the `react router` is pushing every url change to the state and can be easily solve by setting the `replace` property to true while updating the route.

**Comment by utsavdotdev** [comment]
Thank you, @sarojregmi, for reporting this bug. It's a great first issue for anyone new to GitHub, making it an excellent opportunity for beginners to contribute. Could you please also mention this issue on Discord?

**Comment by sarojregmi200** [comment]
Ok why not. 
Can you add a good first issue label and move it to the project.

**Comment by sarojregmi200** [comment]
This issue has been active for very long.
I will be submitting a patch for this bug now.

**Comment by utsavdotdev** [comment]
okie
