### ISSUE TITLE
📚 Docs: Create Code of Conduct document

### ISSUE THREAD

**Issue by utsavdotdev** [GNOME-Nepal/website#25]
#### **Description of the Issue**
The GNOME Nepal website does not currently have a Code of Conduct. This is important because it helps set clear expectations for respectful behavior within the community and prevents misunderstandings. Having a Code of Conduct will ensure that the community stays welcoming, inclusive, and respectful.

#### **Proposed Change or Addition**
Create a new Code of Conduct for the GNOME Nepal community. It should include guidelines for how community members should behave, how to handle conflicts, and how to report issues. The Code of Conduct should be visible on the website and in the repository.

#### **Affected Pages or Sections**
Add a `CODE_OF_CONDUCT.md` file to the root of the repository

#### **Resources**
- [GNOME Code of Conduct](https://conduct.gnome.org)
- [Contributor Covenant](https://www.contributor-covenant.org/)

**Comment by Wasid786** [comment]
I would like to address this issue can you assign this issue to me .

**Comment by utsavdotdev** [comment]
Ok @Wasid786
