### ISSUE TITLE
🐛 Bug report: Broken Discord Invite Link

### ISSUE THREAD

**Issue by Ananya54321** [GNOME-Nepal/website#29]
**Describe the bug**
The invite link to the discord server in both the Navbar and the footer is invalid.

**To Reproduce**
1. Go to 'Navbar'
2. Click on 'Become a member'
3. See error

**Expected behavior**
I expected to be able to get a valid invite link and join the discord community.

**Screenshots**
<img width="1469" alt="Screenshot 2024-10-03 at 1 38 31 AM" src="https://github.com/user-attachments/assets/cd1f7826-57c4-4cc9-8031-1006ba95181a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 129.0.6668.60 (Official Build) (arm64)

**Comment by utsavdotdev** [comment]
@Ananya54321, Thanks for raising it. Can you resolved it ?

**Comment by utsavdotdev** [comment]
Here is the new invitation link:
https://discord.com/invite/tpsVFJN8WC
