### ISSUE TITLE
🚀 Feature request: Dark mode toggle button and its functionality 

### ISSUE THREAD

**Issue by abhishekpanthee** [GNOME-Nepal/website#31]
**Is your feature request related to a problem? Please describe.**
Its not a feature based on a problem . I want to contribute to this project with dark mode toggle button and its functionality 

**Describe the solution you'd like**
I would like to add and toggle icon to switch between light mode and dark mode

Additional Request 
- please label this issue in hacktoberfest-accepted and gssoc

**Comment by utsavdotdev** [comment]
@abhishekpanthee , I have assigned this task to you. It is labeled for Hacktoberfest, and your pull request will be marked as 'hacktoberfest-accepted.'

Please note that to enable dark mode on the website, we are using ShadCN UI, so you can configure it accordingly
