### ISSUE TITLE
[Bug]: Event details padding in mobile devices

### ISSUE THREAD

**Issue by Aadithapa456** [GNOME-Nepal/website#38]
### 📜 Description

When we open the website in mobile device the padding in tab component of event details becomes near zero.

### 👟 Reproduction steps

- Open website in mobile device
- Scroll down to event details section

### 👍 Expected behavior

There should be a good amount of padding on x-axis.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/7ef725a0-202c-43bc-a822-df7bf301424f)

### 💻 Operating system

Something else

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
Thanks for raising it @Aadithapa456, Can you resolve it?
You can replace the text with related icon.

**Comment by Aadithapa456** [comment]
Alright I will try to replace it with related icon.

**Comment by Aadithapa456** [comment]
I fixed it but I used svg for it. If it's okay than I will create a PR, if not than I will try to implement that

**Comment by utsavdotdev** [comment]
No worries, SVG Can be used. You can raise the PR

**Comment by Aadithapa456** [comment]
Alright, I have created two versions one has the library. Let me know if the library one is preferred.
