### ISSUE TITLE
[Bug]: Text overflow in contributions card

### ISSUE THREAD

**Issue by Aadithapa456** [GNOME-Nepal/website#39]
### 📜 Description

When we open the website on a mobile device the person's name inside the contributions card tends to overflow out of the card.

### 👟 Reproduction steps

-Open website in a mobile device
-Scroll down to contributions  section

### 👍 Expected behavior

The text should not overflow

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/e9c85006-b6d2-44e8-a1d3-e04c54075198)

### 💻 Operating system

Something else

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
Assigned
