### ISSUE TITLE
[Bug]: "Become a member" Button not visible in mobile layout

### ISSUE THREAD

**Issue by AnimeshA867** [GNOME-Nepal/website#55]
### 📜 Description

It bugs out when you switch to mobile layout. You can't find the button to become a member.

### 👟 Reproduction steps

Switch To mobile layout

### 👍 Expected behavior

It should still be visible and be part of the navbar options.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/2747742c-2d1d-4e9b-bd51-a165040b88b0)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
@AnimeshA867 assigned to you!

**Comment by utsavdotdev** [comment]
If you stuck anywhere feel free to ask
