### ISSUE TITLE
[Feature]: A page on Active, Completed and Contributing open source projects 

### ISSUE THREAD

**Issue by MegrajChauhan** [GNOME-Nepal/website#61]
### 🔖 Feature description

A page with dedicated sections on the projects that the community is actively working on, has completed(or abandoned or transferred), and is contributing to actively or has contributed to in the past. Each project listed on the sections will expand on the details of the project along with the contributors who worked or are working on them.

### 🎤 Why is this feature needed ?

The page will act as a __report__ for non-technical people or other individuals interested in the community. Anyone willing to sponsor the work of the community shall have their doubts resolved with a quick inspection through this page. This will also act as a proof of skill for the contributors to use in the industry.

### ✌️ How do you aim to achieve this?

The plan is vague but the page should have three sub-sections: one for the list of contributors, one for the community's projects and one for the projects that the community is contributing to. The listing may be done based on discussions with the members and can be expanded with the community's growth.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kshetritej** [comment]
A simple wire frame would be a great help for understanding the requirements. @MegrajChauhan 

Is it like the page for events by Gnome Nepal?

**Comment by MegrajChauhan** [comment]
Nope. I have submitted a PR. You can see for yourself now😁

**Comment by utsavdotdev** [comment]
This section has already been built and will be shipped once we launch the community project.
Preview:
<img width="1277" alt="Screenshot 2024-12-13 at 3 50 17 PM" src="https://github.com/user-attachments/assets/48184017-6de9-4614-99f2-cd5107dc574a" />
