### ISSUE TITLE
[Bug]: Visibility of dates

### ISSUE THREAD

**Issue by n1rjal** [GNOME-Nepal/website#80]
### 📜 Description

Dates is not visible in light mode

### 👟 Reproduction steps

Go to dates of an event in light mode
![image](https://github.com/user-attachments/assets/d13b4103-ee98-4510-9845-16a413a1c13c)

### 👍 Expected behavior

Shouldn't be like this, must be readable
![image](https://github.com/user-attachments/assets/0b146229-0237-4b2f-b00d-04250537f1cb)

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/711b24dc-aead-45c7-99fa-761fe8b5a1a9)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

None

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
Resolved
