### ISSUE TITLE
[Bug]: FAQ section displays two random placeholder boxes even if there are no FAQs.

### ISSUE THREAD

**Issue by fuyalasmit** [GNOME-Nepal/website#87]
### 📜 Description

When the FAQ section is rendered with an empty array (i.e., no FAQs to display), two placeholder boxes are still displayed on the page. This behavior is unexpected, as the section should ideally be hidden or display a message indicating that there are no FAQs available.

![image](https://github.com/user-attachments/assets/b8241828-8107-4781-ab81-267f0d422618)

### 👟 Reproduction steps

1. Navigate to the section where the FAQ section is rendered.
2. Ensure there is no FAQ data available in the FAQ array.
3. Reload the page or trigger the rendering of the FAQ section.
4. Observe the FAQ section on the page.

### 👍 Expected behavior

The FAQ section should not display any placeholder boxes when the FAQ array is empty. Instead, it could either:

1. Hide the FAQ section completely.
2. Display a user-friendly message like "No FAQs available, Contact us if any queries."

### 👎 Actual Behavior with Screenshots

Two empty boxes are displayed in the FAQ section, even though there is no data to populate them.

### 💻 Operating system

Windows

### What browsers are you seeing the problem on?

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🔗 Are you willing to submit PR?

Yes, I am willing to submit a PR!

### 🧑‍⚖️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by utsavdotdev** [comment]
Assigned🚀
